# basic settings for hydra
# here we specify the hydra otputs directory to match the experiment directory
# with this setup hydra will actually create the experiment directory
run:
  dir: "/expts/${run_name}/${run_tag}"
output_subdir: "/expts/${run_name}/${run_tag}/.hydra"