# PyTorch:
#     use nvcr.io/nvidia/pytorch:$nvc_tag for base pytorch NGC
ARG nvc_tag
FROM nvcr.io/nvidia/pytorch:$nvc_tag

# Python packaging -----------------------------------------------------------
RUN python3 -m pip install --no-cache-dir --upgrade pip

# Python packages -------------------------------------------------------------
RUN pip install --no-cache-dir \
    "numpy>=1.22,<1.27" \
    "packaging<=24.2" \
    torchinfo \
    xarray zarr netCDF4 \
    h5py \
    wandb \
    black ruff typer \
    parameterized \
    hydra-core \
    gcsfs \
    seaborn \
    fvcore \
    mpi4py

# torch-harmonics from source ------------------------------------------------
RUN cd /opt && \
    git clone https://github.com/NVIDIA/torch-harmonics.git && \
    cd torch-harmonics && \
    pip install --no-build-isolation -e .

# Clean up
RUN echo "Docker build finished successfully."
